package ui.form.registration;


import genericService.BillService;
import genericService.GuestService;
import genericService.RegistrationService;
import genericService.RoomService;
import java.util.Date;
import serviceImpl.BillServiceImpl;
import serviceImpl.GuestServiceImpl;
import serviceImpl.RegistrationServiceImpl;
import serviceImpl.RoomServiceImpl;
import ui.form.guest.GuestAddForm;
import ui.form.registration.controler.RegistrationAddFormControler;

/**
 *
 * @author Jelena Basaric
 */
public class RegistrationAddForm extends javax.swing.JDialog {

    RegistrationService registrationService;
    RoomService roomService;
    GuestService guestService;
    BillService billService;
    
  
    

    /**
     * Creates new form RegistrationAddForm
     */
    public RegistrationAddForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(this.getMaximumSize());
        setLocationRelativeTo(null);
        registrationService = new RegistrationServiceImpl();
        roomService= new RoomServiceImpl();
        guestService=new GuestServiceImpl();
        billService=new BillServiceImpl();
        prepareForm();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipSobe = new javax.swing.ButtonGroup();
        pnlRegistration = new javax.swing.JPanel();
        btnOnebad = new javax.swing.JRadioButton();
        rbtnTwobad = new javax.swing.JRadioButton();
        rbtnThreeBad = new javax.swing.JRadioButton();
        rbtnFourBad = new javax.swing.JRadioButton();
        rbtnApartman = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cmbRoomNo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateRegistration = new com.toedter.calendar.JDateChooser();
        jDateEstDepartureDate = new com.toedter.calendar.JDateChooser();
        jDateDepartureDate = new com.toedter.calendar.JDateChooser();
        btnSelectGuest = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumAdults = new javax.swing.JTextField();
        txtNumChildren = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSpecReq = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        cmbGuests = new javax.swing.JComboBox<>();
        btnAddguest = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        pnlGuests = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuest = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlRegistration.setBackground(new java.awt.Color(204, 204, 204));
        pnlRegistration.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Podaci o registraciji", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        btnGroupTipSobe.add(btnOnebad);
        btnOnebad.setText("JEDNOKREVETNA");
        btnOnebad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnebadActionPerformed(evt);
            }
        });

        btnGroupTipSobe.add(rbtnTwobad);
        rbtnTwobad.setText("DVOKREVETNA");
        rbtnTwobad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTwobadActionPerformed(evt);
            }
        });

        btnGroupTipSobe.add(rbtnThreeBad);
        rbtnThreeBad.setText("TROKREVETNA");
        rbtnThreeBad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnThreeBadActionPerformed(evt);
            }
        });

        btnGroupTipSobe.add(rbtnFourBad);
        rbtnFourBad.setText("ČETVOROKREVETNA");
        rbtnFourBad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFourBadActionPerformed(evt);
            }
        });

        btnGroupTipSobe.add(rbtnApartman);
        rbtnApartman.setText("APARTMAN");
        rbtnApartman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnApartmanActionPerformed(evt);
            }
        });

        jLabel1.setText("Broj sobe");

        jLabel3.setText("Datum registracije");

        jLabel4.setText("Datum planirane odjave");

        jLabel5.setText("Datum odjave");

        jDateRegistration.setDateFormatString("dd.MM.yyyy.");

        jDateEstDepartureDate.setDateFormatString("dd.MM.yyyy.");

        jDateDepartureDate.setDateFormatString("dd.MM.yyyy.");

        btnSelectGuest.setText("Izaberi gosta");
        btnSelectGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectGuestActionPerformed(evt);
            }
        });

        jLabel6.setText("Broj odraslih");

        jLabel7.setText("Broj dece do 8 godina");

        jLabel8.setText("Posebni zahtevi");

        txtSpecReq.setColumns(20);
        txtSpecReq.setRows(5);
        jScrollPane2.setViewportView(txtSpecReq);

        jLabel9.setText("Izaberi gosta");

        btnAddguest.setText("Dodaj gosta");
        btnAddguest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddguestActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlRegistrationLayout = new javax.swing.GroupLayout(pnlRegistration);
        pnlRegistration.setLayout(pnlRegistrationLayout);
        pnlRegistrationLayout.setHorizontalGroup(
            pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrationLayout.createSequentialGroup()
                        .addComponent(btnOnebad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnTwobad)
                        .addGap(35, 35, 35)
                        .addComponent(rbtnThreeBad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnFourBad))
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegistrationLayout.createSequentialGroup()
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateRegistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDateEstDepartureDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDateDepartureDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistrationLayout.createSequentialGroup()
                                .addComponent(cmbGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSelectGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddguest, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegistrationLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRegistrationLayout.createSequentialGroup()
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbtnApartman)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumAdults)
                            .addComponent(txtNumChildren, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegistrationLayout.setVerticalGroup(
            pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrationLayout.createSequentialGroup()
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOnebad)
                    .addComponent(rbtnTwobad)
                    .addComponent(rbtnThreeBad)
                    .addComponent(rbtnFourBad)
                    .addComponent(rbtnApartman))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumAdults, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrationLayout.createSequentialGroup()
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumChildren))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pnlRegistrationLayout.createSequentialGroup()
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistrationLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jDateRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateEstDepartureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateDepartureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelectGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddguest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlGuests.setBackground(new java.awt.Color(204, 204, 204));
        pnlGuests.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gosti sobe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        tblGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGuest);

        javax.swing.GroupLayout pnlGuestsLayout = new javax.swing.GroupLayout(pnlGuests);
        pnlGuests.setLayout(pnlGuestsLayout);
        pnlGuestsLayout.setHorizontalGroup(
            pnlGuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlGuestsLayout.setVerticalGroup(
            pnlGuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuestsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Sačuvaj");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Odustani");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlGuests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectGuestActionPerformed
        new GuestAddForm(null, true).setVisible(true);
    }//GEN-LAST:event_btnSelectGuestActionPerformed

    private void btnOnebadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnebadActionPerformed
        //  RoomTypeEnum roomTypeEnum=RoomTypeEnum.valueOf(btnOnebad.getText().toString());
        populateCmbRoom();
    }//GEN-LAST:event_btnOnebadActionPerformed

    private void rbtnThreeBadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnThreeBadActionPerformed
        //RoomTypeEnum roomTypeEnum=RoomTypeEnum.valueOf(rbtnThreeBad.getText().toString());
        populateCmbRoom();        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnThreeBadActionPerformed

    private void rbtnFourBadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFourBadActionPerformed
        populateCmbRoom();
    }//GEN-LAST:event_rbtnFourBadActionPerformed

    private void rbtnApartmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnApartmanActionPerformed
        //RoomTypeEnum roomTypeEnum=RoomTypeEnum.valueOf(rbtnApartman.getText().toString());
        populateCmbRoom();        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnApartmanActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       RegistrationAddFormControler.addRegistration(jDateDepartureDate,jDateRegistration,jDateEstDepartureDate,lblError,cmbGuests,cmbRoomNo,txtNumAdults,txtNumChildren,txtSpecReq,registrationService,guestService,billService,roomService,this);
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void rbtnTwobadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTwobadActionPerformed
        populateCmbRoom();
        
// TODO add your handling code here:
    }//GEN-LAST:event_rbtnTwobadActionPerformed

    private void btnAddguestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddguestActionPerformed
       RegistrationAddFormControler.addGuestInRoom(tblGuest,txtNumAdults,cmbRoomNo,cmbGuests,this);
              
    }//GEN-LAST:event_btnAddguestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddguest;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGroupTipSobe;
    private javax.swing.JRadioButton btnOnebad;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelectGuest;
    private javax.swing.JComboBox<domain.Guest> cmbGuests;
    private javax.swing.JComboBox<domain.Room> cmbRoomNo;
    private com.toedter.calendar.JDateChooser jDateDepartureDate;
    private com.toedter.calendar.JDateChooser jDateEstDepartureDate;
    private com.toedter.calendar.JDateChooser jDateRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JPanel pnlGuests;
    private javax.swing.JPanel pnlRegistration;
    private javax.swing.JRadioButton rbtnApartman;
    private javax.swing.JRadioButton rbtnFourBad;
    private javax.swing.JRadioButton rbtnThreeBad;
    private javax.swing.JRadioButton rbtnTwobad;
    private javax.swing.JTable tblGuest;
    private javax.swing.JTextField txtNumAdults;
    private javax.swing.JTextField txtNumChildren;
    private javax.swing.JTextArea txtSpecReq;
    // End of variables declaration//GEN-END:variables

    private void populateCmbRoom() {
        RegistrationAddFormControler.populateCmbRoom(cmbRoomNo,txtNumAdults,txtNumChildren,rbtnApartman,rbtnFourBad,rbtnThreeBad,rbtnTwobad,btnOnebad);
    }

    private void prepareForm() {
        populateCmbRoom();
        populateCmbGuest();
        Date date = new Date();
        jDateRegistration.setDate(date);
        txtNumChildren.setText("0");
        txtSpecReq.setText("nema");
    }

    private void populateCmbGuest() {
        RegistrationAddFormControler.populateComboGuest(cmbGuests);
    }
}
