/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.main.form;

import javax.swing.JFrame;
import domain.UserProfile;
import applicationSession.ApplicationSession;
import domain.Hotel;
import domain.Room;
import domain.RoomType;
import domain.RoomTypeEnum;
import genericService.HotelService;
import java.awt.Color;
import serviceImpl.HotelServiceImpl;
import ui.form.Hotel.HotelDetailsForm;
import ui.form.Room.RoomDetailsForm;
import ui.form.Room.RoomSearchForm;
import ui.form.city.CityAddForm;
import ui.form.city.CitySearchForm;
import ui.form.country.CountryAddForm;
import ui.form.country.CountrySearchForm;
import ui.form.employee.EmployeeAddForm;
import ui.form.employee.EmployeeSearchForm;
import ui.form.guest.GuestAddForm;
import ui.form.guest.GuestSearchForm;
import ui.form.registration.RegistrationAddForm;

/**
 *
 * @author Jelena Basaric
 */
public class MainForm extends javax.swing.JFrame {
    private HotelService hotelService;
    private Room r=new Room();
    private RoomType roomType=new RoomType();
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        setBackground(Color.orange);
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        hotelService=new HotelServiceImpl();       
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        lblUser = new javax.swing.JLabel();
        pnlHotel = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnOneBT = new javax.swing.JButton();
        ttnThrBT = new javax.swing.JButton();
        btnFourBT = new javax.swing.JButton();
        btnTwoBT = new javax.swing.JButton();
        btnAT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn1BBizzy = new javax.swing.JButton();
        btn3BBizzy = new javax.swing.JButton();
        btn4BBizzy = new javax.swing.JButton();
        btn2BBizzy = new javax.swing.JButton();
        btnApartmanBizzy = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        registrationMenu = new javax.swing.JMenu();
        registrationMenuAddItem = new javax.swing.JMenuItem();
        roomMenu = new javax.swing.JMenu();
        roomMenuDetalistItem = new javax.swing.JMenuItem();
        guestMenu = new javax.swing.JMenu();
        guestMenuSearchItem = new javax.swing.JMenuItem();
        guestMenuAddItem = new javax.swing.JMenuItem();
        countryMenu = new javax.swing.JMenu();
        countryMenuSearchItem = new javax.swing.JMenuItem();
        countryMenuAddItem = new javax.swing.JMenuItem();
        cityMenu = new javax.swing.JMenu();
        cityMenuSeachItem = new javax.swing.JMenuItem();
        cityMenuAddItem = new javax.swing.JMenuItem();
        employeeMenu = new javax.swing.JMenu();
        employeeMenuAddItem = new javax.swing.JMenuItem();
        employeeMenuSearchItem = new javax.swing.JMenuItem();
        hotelMenu = new javax.swing.JMenu();
        hotelMenuDetailistItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacija Hotel");
        setBackground(new java.awt.Color(255, 255, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 153));
        setName("MainForm"); // NOI18N

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUser.setText("jLabel1");

        pnlHotel.setBackground(new java.awt.Color(204, 204, 0));
        pnlHotel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Podaci o hotelu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 16))); // NOI18N

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAddress.setEditable(false);
        txtAddress.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        txtCity.setEditable(false);
        txtCity.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        txtPhoneNo.setEditable(false);
        txtPhoneNo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        javax.swing.GroupLayout pnlHotelLayout = new javax.swing.GroupLayout(pnlHotel);
        pnlHotel.setLayout(pnlHotelLayout);
        pnlHotelLayout.setHorizontalGroup(
            pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName)
                    .addComponent(txtAddress)
                    .addComponent(txtCity)
                    .addComponent(txtPhoneNo)
                    .addComponent(txtEmail))
                .addContainerGap())
        );
        pnlHotelLayout.setVerticalGroup(
            pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotelLayout.createSequentialGroup()
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setForeground(new java.awt.Color(204, 204, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotelIkona.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SLOBODNE SOBE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        btnOneBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOneBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/jednokrevetna.jpg"))); // NOI18N
        btnOneBT.setText("JEDNOKREVETNA");
        btnOneBT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JEDNOKREVETNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        btnOneBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneBTActionPerformed(evt);
            }
        });

        ttnThrBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/trokrevetna.jpg"))); // NOI18N
        ttnThrBT.setText("jButton2");
        ttnThrBT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TROKREVETNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        ttnThrBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttnThrBTActionPerformed(evt);
            }
        });

        btnFourBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cetvorokrevetna.jpg"))); // NOI18N
        btnFourBT.setText("jButton2");
        btnFourBT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ČETVOREKREVETNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        btnFourBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourBTActionPerformed(evt);
            }
        });

        btnTwoBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dvokrevetna.jpg"))); // NOI18N
        btnTwoBT.setText("jButton2");
        btnTwoBT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DVOKREVETNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        btnTwoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoBTActionPerformed(evt);
            }
        });

        btnAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/apartman2.jpg"))); // NOI18N
        btnAT.setText("jButton2");
        btnAT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APARTMAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        btnAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ttnThrBT, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFourBT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTwoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAT, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTwoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnOneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttnThrBT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFourBT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ZAUZETE SOBE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        btn1BBizzy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn1BBizzy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/jednokrevetna.jpg"))); // NOI18N
        btn1BBizzy.setText("JEDNOKREVETNA");
        btn1BBizzy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JEDNOKREVETNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        btn1BBizzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1BBizzyActionPerformed(evt);
            }
        });

        btn3BBizzy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/trokrevetna.jpg"))); // NOI18N
        btn3BBizzy.setText("jButton2");
        btn3BBizzy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TROKREVETNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        btn3BBizzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3BBizzyActionPerformed(evt);
            }
        });

        btn4BBizzy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cetvorokrevetna.jpg"))); // NOI18N
        btn4BBizzy.setText("jButton2");
        btn4BBizzy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ČETVOREKREVETNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        btn4BBizzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4BBizzyActionPerformed(evt);
            }
        });

        btn2BBizzy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dvokrevetna.jpg"))); // NOI18N
        btn2BBizzy.setText("jButton2");
        btn2BBizzy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DVOKREVETNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        btn2BBizzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2BBizzyActionPerformed(evt);
            }
        });

        btnApartmanBizzy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/apartman2.jpg"))); // NOI18N
        btnApartmanBizzy.setText("jButton2");
        btnApartmanBizzy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APARTMAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        btnApartmanBizzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApartmanBizzyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn3BBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1BBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4BBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn2BBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApartmanBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApartmanBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn2BBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn1BBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3BBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4BBizzy, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        registrationMenu.setText("Registracija");

        registrationMenuAddItem.setText("Nova registracija");
        registrationMenuAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationMenuAddItemActionPerformed(evt);
            }
        });
        registrationMenu.add(registrationMenuAddItem);

        jMenuBar1.add(registrationMenu);

        roomMenu.setText("Soba");

        roomMenuDetalistItem.setText("Lista soba");
        roomMenuDetalistItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomMenuDetalistItemActionPerformed(evt);
            }
        });
        roomMenu.add(roomMenuDetalistItem);

        jMenuBar1.add(roomMenu);

        guestMenu.setText("Gost");

        guestMenuSearchItem.setText("Pregled gostiju");
        guestMenuSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestMenuSearchItemActionPerformed(evt);
            }
        });
        guestMenu.add(guestMenuSearchItem);

        guestMenuAddItem.setText("Dodaj novog gosta");
        guestMenuAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestMenuAddItemActionPerformed(evt);
            }
        });
        guestMenu.add(guestMenuAddItem);

        jMenuBar1.add(guestMenu);

        countryMenu.setText("Drzave");

        countryMenuSearchItem.setText("Pregled svih drzava");
        countryMenuSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryMenuSearchItemActionPerformed(evt);
            }
        });
        countryMenu.add(countryMenuSearchItem);

        countryMenuAddItem.setText("Dodaj novu drzavu");
        countryMenuAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryMenuAddItemActionPerformed(evt);
            }
        });
        countryMenu.add(countryMenuAddItem);

        jMenuBar1.add(countryMenu);

        cityMenu.setBackground(new java.awt.Color(255, 255, 153));
        cityMenu.setText(" Gradovi");

        cityMenuSeachItem.setText("Pregled svih gradova");
        cityMenuSeachItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityMenuSeachItemActionPerformed(evt);
            }
        });
        cityMenu.add(cityMenuSeachItem);

        cityMenuAddItem.setText("Dodaj novi grad");
        cityMenuAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityMenuAddItemActionPerformed(evt);
            }
        });
        cityMenu.add(cityMenuAddItem);

        jMenuBar1.add(cityMenu);

        employeeMenu.setText("Zaposleni");

        employeeMenuAddItem.setText("Novi");
        employeeMenuAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeMenuAddItemActionPerformed(evt);
            }
        });
        employeeMenu.add(employeeMenuAddItem);

        employeeMenuSearchItem.setText("Pretraga");
        employeeMenuSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeMenuSearchItemActionPerformed(evt);
            }
        });
        employeeMenu.add(employeeMenuSearchItem);

        jMenuBar1.add(employeeMenu);

        hotelMenu.setText("Hotel_info");

        hotelMenuDetailistItem.setText(" Podaci o hotelu");
        hotelMenuDetailistItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelMenuDetailistItemActionPerformed(evt);
            }
        });
        hotelMenu.add(hotelMenuDetailistItem);

        jMenuBar1.add(hotelMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(pnlHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countryMenuSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryMenuSearchItemActionPerformed
        new CountrySearchForm(this, true).setVisible(true);
       /*JFrame nova=new novaForm();
        nova.setVisible(true);*/
                
    }//GEN-LAST:event_countryMenuSearchItemActionPerformed

    private void cityMenuSeachItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityMenuSeachItemActionPerformed
       new CitySearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_cityMenuSeachItemActionPerformed

    private void countryMenuAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryMenuAddItemActionPerformed
       new CountryAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_countryMenuAddItemActionPerformed

    private void cityMenuAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityMenuAddItemActionPerformed
       new CityAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_cityMenuAddItemActionPerformed

    private void employeeMenuSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeMenuSearchItemActionPerformed
        new EmployeeSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_employeeMenuSearchItemActionPerformed

    private void employeeMenuAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeMenuAddItemActionPerformed
        new EmployeeAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_employeeMenuAddItemActionPerformed

    private void guestMenuAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestMenuAddItemActionPerformed
        new GuestAddForm(this,true).setVisible(true);
    }//GEN-LAST:event_guestMenuAddItemActionPerformed

    private void hotelMenuDetailistItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelMenuDetailistItemActionPerformed
        new HotelDetailsForm(this, true).setVisible(true);
    }//GEN-LAST:event_hotelMenuDetailistItemActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your hanttdling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void guestMenuSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestMenuSearchItemActionPerformed
        new GuestSearchForm(this,true).setVisible(true);
    }//GEN-LAST:event_guestMenuSearchItemActionPerformed

    private void roomMenuDetalistItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomMenuDetalistItemActionPerformed
        new RoomSearchForm(this,true).setVisible(true);
    }//GEN-LAST:event_roomMenuDetalistItemActionPerformed

    private void registrationMenuAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationMenuAddItemActionPerformed
        new RegistrationAddForm(this,true).setVisible(true);
    }//GEN-LAST:event_registrationMenuAddItemActionPerformed

    private void btnTwoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoBTActionPerformed
        
        roomType.setRoomTypeName(RoomTypeEnum.DVOKREVETNA);
        ListRoomAvailable();
    }//GEN-LAST:event_btnTwoBTActionPerformed

    private void btn2BBizzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2BBizzyActionPerformed
         roomType.setRoomTypeName(RoomTypeEnum.DVOKREVETNA);
        ListRoomNotAvilable();
      
       
    }//GEN-LAST:event_btn2BBizzyActionPerformed

    private void btnOneBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneBTActionPerformed
        roomType.setRoomTypeName(RoomTypeEnum.JEDNOKREVETNA);
        ListRoomAvailable();
    }//GEN-LAST:event_btnOneBTActionPerformed

    private void btn1BBizzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1BBizzyActionPerformed
        roomType.setRoomTypeName(RoomTypeEnum.JEDNOKREVETNA);
        ListRoomNotAvilable();
    }//GEN-LAST:event_btn1BBizzyActionPerformed

    private void ttnThrBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttnThrBTActionPerformed
        roomType.setRoomTypeName(RoomTypeEnum.TROKREVETNA);
        ListRoomAvailable();
    }//GEN-LAST:event_ttnThrBTActionPerformed

    private void btnFourBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourBTActionPerformed
       roomType.setRoomTypeName(RoomTypeEnum.CETVOROKREVETNA);
        ListRoomAvailable();
    }//GEN-LAST:event_btnFourBTActionPerformed

    private void btnATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnATActionPerformed
      roomType.setRoomTypeName(RoomTypeEnum.APARTMAN);
        ListRoomAvailable();
    }//GEN-LAST:event_btnATActionPerformed

    private void btnApartmanBizzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApartmanBizzyActionPerformed
         roomType.setRoomTypeName(RoomTypeEnum.APARTMAN);
        ListRoomNotAvilable();
    }//GEN-LAST:event_btnApartmanBizzyActionPerformed

    private void btn3BBizzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3BBizzyActionPerformed
         roomType.setRoomTypeName(RoomTypeEnum.TROKREVETNA);
        ListRoomNotAvilable();
    }//GEN-LAST:event_btn3BBizzyActionPerformed

    private void btn4BBizzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4BBizzyActionPerformed
        roomType.setRoomTypeName(RoomTypeEnum.CETVOROKREVETNA);
        ListRoomNotAvilable();
    }//GEN-LAST:event_btn4BBizzyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1BBizzy;
    private javax.swing.JButton btn2BBizzy;
    private javax.swing.JButton btn3BBizzy;
    private javax.swing.JButton btn4BBizzy;
    private javax.swing.JButton btnAT;
    private javax.swing.JButton btnApartmanBizzy;
    private javax.swing.JButton btnFourBT;
    private javax.swing.JButton btnOneBT;
    private javax.swing.JButton btnTwoBT;
    private javax.swing.JMenu cityMenu;
    private javax.swing.JMenuItem cityMenuAddItem;
    private javax.swing.JMenuItem cityMenuSeachItem;
    private javax.swing.JMenu countryMenu;
    private javax.swing.JMenuItem countryMenuAddItem;
    private javax.swing.JMenuItem countryMenuSearchItem;
    private javax.swing.JMenu employeeMenu;
    private javax.swing.JMenuItem employeeMenuAddItem;
    private javax.swing.JMenuItem employeeMenuSearchItem;
    private javax.swing.JMenu guestMenu;
    private javax.swing.JMenuItem guestMenuAddItem;
    private javax.swing.JMenuItem guestMenuSearchItem;
    private javax.swing.JMenu hotelMenu;
    private javax.swing.JMenuItem hotelMenuDetailistItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlHotel;
    private javax.swing.JMenu registrationMenu;
    private javax.swing.JMenuItem registrationMenuAddItem;
    private javax.swing.JMenu roomMenu;
    private javax.swing.JMenuItem roomMenuDetalistItem;
    private javax.swing.JButton ttnThrBT;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
      UserProfile userProfile = ApplicationSession.getInstance().getLoginUser();
        this.lblUser.setText("Prijavljeni ste kao:" + userProfile.getEmployee().getFirstName()+", " + userProfile.getEmployee().getLastName());
        
        //ako korisnik ima ulogu administaror prikazati mu meni gradovi i meni drzave
        if (userProfile.isAdmin()){
            cityMenu.setEnabled(true);
            countryMenu.setEnabled(true);
        }else{
            cityMenu.setEnabled(false);
            countryMenu.setEnabled(false);
        }
        Hotel hotel=hotelService.find();
        txtName.setText(hotel.getName());
        txtCity.setText(hotel.getCity().toString());
        txtAddress.setText(hotel.getAddress());
        txtEmail.setText(hotel.getEmail());
        txtPhoneNo.setText(hotel.getPhoneNumber());        
           }

    private void ListRoomAvailable() {
        r.setRoomType(roomType);
        r.setOccupancy(true);
        ApplicationSession.getInstance().setRoom(r);
        new RoomDetailsForm(this,true).setVisible(true);
    }
    private void ListRoomNotAvilable(){
        r.setRoomType(roomType);
        r.setOccupancy(false);
        ApplicationSession.getInstance().setRoom(r);
        new RoomDetailsForm(this,true).setVisible(true);
    }
}
